### ISSUE TITLE
Tradução para pt_BR

### ISSUE THREAD

**Issue by daniofilho** [claudiosmweb/woocommerce-domination#3]
Não tenho certeza se poderia enviar PR disso, mas uso o plugin e precisei traduzi-lo.

Caso tenha interesse, segue arquivo da tradução:

[woocommerce-domination-pt_BR.zip](https://github.com/claudiosmweb/woocommerce-domination/files/238928/woocommerce-domination-pt_BR.zip)

**Comment by claudiosmweb** [comment]
Na verdade estou para habilitar ele no translate.wordpress.org e assim fica mais fácil.

**Comment by daniofilho** [comment]
Tranquilo, me avise se precisar de ajuda.

Obrigado!
